package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AclientsadressesId generated by hbm2java
 */
@Embeddable
public class AclientsadressesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6122446298811638377L;
	private Integer idClient;
	private Integer idAdresse;

	public AclientsadressesId() {
	}

	public AclientsadressesId(Integer idClient, Integer idAdresse) {
		this.idClient = idClient;
		this.idAdresse = idAdresse;
	}

	@Column(name = "idClient")
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idAdresse")
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AclientsadressesId))
			return false;
		AclientsadressesId castOther = (AclientsadressesId) other;

		return ((this.getIdClient() == castOther.getIdClient()) || (this
				.getIdClient() != null
				&& castOther.getIdClient() != null && this.getIdClient()
				.equals(castOther.getIdClient())))
				&& ((this.getIdAdresse() == castOther.getIdAdresse()) || (this
						.getIdAdresse() != null
						&& castOther.getIdAdresse() != null && this
						.getIdAdresse().equals(castOther.getIdAdresse())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdClient() == null ? 0 : this.getIdClient().hashCode());
		result = 37 * result
				+ (getIdAdresse() == null ? 0 : this.getIdAdresse().hashCode());
		return result;
	}

}
