package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Acommandesproduits generated by hbm2java
 */
@Entity
@Table(name = "acommandesproduits", catalog = "corepharma")
public class Acommandesproduits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1206355762733802794L;
	private AcommandesproduitsId id;

	public Acommandesproduits() {
	}

	public Acommandesproduits(AcommandesproduitsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idProduit", column = @Column(name = "idProduit")),
			@AttributeOverride(name = "idCommande", column = @Column(name = "idCommande")) })
	public AcommandesproduitsId getId() {
		return this.id;
	}

	public void setId(AcommandesproduitsId id) {
		this.id = id;
	}

}
