package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Aforunisseursadresses generated by hbm2java
 */
@Entity
@Table(name = "aforunisseursadresses", catalog = "corepharma")
public class Aforunisseursadresses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8770112305688179663L;
	private AforunisseursadressesId id;

	public Aforunisseursadresses() {
	}

	public Aforunisseursadresses(AforunisseursadressesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idFournisseur", column = @Column(name = "idFournisseur")),
			@AttributeOverride(name = "idAdresse", column = @Column(name = "idAdresse")) })
	public AforunisseursadressesId getId() {
		return this.id;
	}

	public void setId(AforunisseursadressesId id) {
		this.id = id;
	}

}
