package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Aproduitsventes generated by hbm2java
 */
@Entity
@Table(name = "aproduitsventes", catalog = "corepharma")
public class Aproduitsventes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3031872911326388760L;
	private AproduitsventesId id;

	public Aproduitsventes() {
	}

	public Aproduitsventes(AproduitsventesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idVente", column = @Column(name = "idVente")),
			@AttributeOverride(name = "idProduit", column = @Column(name = "idProduit")) })
	public AproduitsventesId getId() {
		return this.id;
	}

	public void setId(AproduitsventesId id) {
		this.id = id;
	}

}
