package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Assocommandesproduits generated by hbm2java
 */
@Entity
@Table(name = "assocommandesproduits", catalog = "corepharma")
public class Assocommandesproduits implements java.io.Serializable {

	private AssocommandesproduitsId id;

	public Assocommandesproduits() {
	}

	public Assocommandesproduits(AssocommandesproduitsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idCommande", column = @Column(name = "idCommande")),
			@AttributeOverride(name = "idProduit", column = @Column(name = "idProduit")) })
	public AssocommandesproduitsId getId() {
		return this.id;
	}

	public void setId(AssocommandesproduitsId id) {
		this.id = id;
	}

}
