package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Assoventesproduits generated by hbm2java
 */
@Entity
@Table(name = "assoventesproduits", catalog = "corepharma")
public class Assoventesproduits implements java.io.Serializable {

	private AssoventesproduitsId id;

	public Assoventesproduits() {
	}

	public Assoventesproduits(AssoventesproduitsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idVente", column = @Column(name = "idVente")),
			@AttributeOverride(name = "idProduit", column = @Column(name = "idProduit")) })
	public AssoventesproduitsId getId() {
		return this.id;
	}

	public void setId(AssoventesproduitsId id) {
		this.id = id;
	}

}
