package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Assoclientscomptesbancaires generated by hbm2java
 */
@Entity
@Table(name = "assoclientscomptesbancaires", catalog = "corepharma")
public class Assoclientscomptesbancaires implements java.io.Serializable {

	private AssoclientscomptesbancairesId id;

	public Assoclientscomptesbancaires() {
	}

	public Assoclientscomptesbancaires(AssoclientscomptesbancairesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idClient", column = @Column(name = "idClient")),
			@AttributeOverride(name = "idCompte", column = @Column(name = "idCompte")) })
	public AssoclientscomptesbancairesId getId() {
		return this.id;
	}

	public void setId(AssoclientscomptesbancairesId id) {
		this.id = id;
	}

}
