package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Assosfournisseurscomptesbancaires generated by hbm2java
 */
@Entity
@Table(name = "assosfournisseurscomptesbancaires", catalog = "corepharma")
public class Assosfournisseurscomptesbancaires implements java.io.Serializable {

	private AssosfournisseurscomptesbancairesId id;

	public Assosfournisseurscomptesbancaires() {
	}

	public Assosfournisseurscomptesbancaires(
			AssosfournisseurscomptesbancairesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idFournisseur", column = @Column(name = "idFournisseur")),
			@AttributeOverride(name = "idCompte", column = @Column(name = "idCompte")) })
	public AssosfournisseurscomptesbancairesId getId() {
		return this.id;
	}

	public void setId(AssosfournisseurscomptesbancairesId id) {
		this.id = id;
	}

}
