package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commandes generated by hbm2java
 */
@Entity
@Table(name = "commandes", catalog = "corepharma")
public class Commandes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idCommande;
	private Integer idMode;
	private Integer idClient;
	private Integer idGestion;
	private Integer idEtat;
	private Integer idFournisseur;
	private Integer idAlarme;
	private String numeroCommande;
	private String idFournisseurCommande;
	private String etatCommande;
	private String dateLivraisonSouhaite;
	private String dateLivraisonEffective;
	private String dateCreation;
	private String dateModification;
	private String idAuteurCreation;
	private String idAuteurModification;
	private Set<Produits> commandesProduits;

	public Commandes() {
	}

	public Commandes(Integer idMode, Integer idClient, Integer idGestion,
			Integer idEtat, Integer idFournisseur, Integer idAlarme,
			String numeroCommande, String idFournisseurCommande,
			String etatCommande, String dateLivraisonSouhaite,
			String dateLivraisonEffective, String dateCreation,
			String dateModification, String idAuteurCreation,
			String idAuteurModification) {
		this.idMode = idMode;
		this.idClient = idClient;
		this.idGestion = idGestion;
		this.idEtat = idEtat;
		this.idFournisseur = idFournisseur;
		this.idAlarme = idAlarme;
		this.numeroCommande = numeroCommande;
		this.idFournisseurCommande = idFournisseurCommande;
		this.etatCommande = etatCommande;
		this.dateLivraisonSouhaite = dateLivraisonSouhaite;
		this.dateLivraisonEffective = dateLivraisonEffective;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.idAuteurCreation = idAuteurCreation;
		this.idAuteurModification = idAuteurModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCommande", unique = true, nullable = false)
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	@Column(name = "idMode")
	public Integer getIdMode() {
		return this.idMode;
	}

	public void setIdMode(Integer idMode) {
		this.idMode = idMode;
	}

	@Column(name = "idClient")
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idGestion")
	public Integer getIdGestion() {
		return this.idGestion;
	}

	public void setIdGestion(Integer idGestion) {
		this.idGestion = idGestion;
	}

	@Column(name = "idEtat")
	public Integer getIdEtat() {
		return this.idEtat;
	}

	public void setIdEtat(Integer idEtat) {
		this.idEtat = idEtat;
	}

	@Column(name = "idFournisseur")
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "idAlarme")
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "numeroCommande", length = 254)
	public String getNumeroCommande() {
		return this.numeroCommande;
	}

	public void setNumeroCommande(String numeroCommande) {
		this.numeroCommande = numeroCommande;
	}

	@Column(name = "idFournisseurCommande", length = 254)
	public String getIdFournisseurCommande() {
		return this.idFournisseurCommande;
	}

	public void setIdFournisseurCommande(String idFournisseurCommande) {
		this.idFournisseurCommande = idFournisseurCommande;
	}

	@Column(name = "etatCommande", length = 254)
	public String getEtatCommande() {
		return this.etatCommande;
	}

	public void setEtatCommande(String etatCommande) {
		this.etatCommande = etatCommande;
	}

	@Column(name = "dateLivraisonSouhaite", length = 254)
	public String getDateLivraisonSouhaite() {
		return this.dateLivraisonSouhaite;
	}

	public void setDateLivraisonSouhaite(String dateLivraisonSouhaite) {
		this.dateLivraisonSouhaite = dateLivraisonSouhaite;
	}

	@Column(name = "dateLivraisonEffective", length = 254)
	public String getDateLivraisonEffective() {
		return this.dateLivraisonEffective;
	}

	public void setDateLivraisonEffective(String dateLivraisonEffective) {
		this.dateLivraisonEffective = dateLivraisonEffective;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "idAuteurCreation", length = 254)
	public String getIdAuteurCreation() {
		return this.idAuteurCreation;
	}

	public void setIdAuteurCreation(String idAuteurCreation) {
		this.idAuteurCreation = idAuteurCreation;
	}

	@Column(name = "idAuteurModification", length = 254)
	public String getIdAuteurModification() {
		return this.idAuteurModification;
	}

	public void setIdAuteurModification(String idAuteurModification) {
		this.idAuteurModification = idAuteurModification;
	}

	public Set<Produits> getCommandesProduits() {
		return commandesProduits;
	}

	public void setCommandesProduits(Set<Produits> commandesProduits) {
		this.commandesProduits = commandesProduits;
	}
	
	

}
