package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Commandes generated by hbm2java
 */
@Entity
@Table(name = "commandes", catalog = "corepharma")
public class Commandes implements java.io.Serializable {

	private Integer idCommande;
	private Integer idFournisseur;
	private Integer idMode;
	private Integer idClient;
	private Integer idAlarme;
	private Integer idEtat;
	private String numeroCommande;
	private String etatCommande;
	private String dateLivraisonSouhaite;
	private String dateLivraisonEffective;
	private String dateCreation;
	private String dateModification;
	private Integer idAuteurCreation;
	private Integer idAuteurModification;

	public Commandes() {
	}

	public Commandes(Integer idFournisseur, Integer idMode, Integer idClient,
			Integer idAlarme, Integer idEtat, String numeroCommande,
			String etatCommande, String dateLivraisonSouhaite,
			String dateLivraisonEffective, String dateCreation,
			String dateModification, Integer idAuteurCreation,
			Integer idAuteurModification) {
		this.idFournisseur = idFournisseur;
		this.idMode = idMode;
		this.idClient = idClient;
		this.idAlarme = idAlarme;
		this.idEtat = idEtat;
		this.numeroCommande = numeroCommande;
		this.etatCommande = etatCommande;
		this.dateLivraisonSouhaite = dateLivraisonSouhaite;
		this.dateLivraisonEffective = dateLivraisonEffective;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.idAuteurCreation = idAuteurCreation;
		this.idAuteurModification = idAuteurModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCommande", unique = true, nullable = false)
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	@Column(name = "idFournisseur")
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "idMode")
	public Integer getIdMode() {
		return this.idMode;
	}

	public void setIdMode(Integer idMode) {
		this.idMode = idMode;
	}

	@Column(name = "idClient")
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idAlarme")
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "idEtat")
	public Integer getIdEtat() {
		return this.idEtat;
	}

	public void setIdEtat(Integer idEtat) {
		this.idEtat = idEtat;
	}

	@Column(name = "numeroCommande", length = 254)
	public String getNumeroCommande() {
		return this.numeroCommande;
	}

	public void setNumeroCommande(String numeroCommande) {
		this.numeroCommande = numeroCommande;
	}

	@Column(name = "etatCommande", length = 254)
	public String getEtatCommande() {
		return this.etatCommande;
	}

	public void setEtatCommande(String etatCommande) {
		this.etatCommande = etatCommande;
	}

	@Column(name = "dateLivraisonSouhaite", length = 254)
	public String getDateLivraisonSouhaite() {
		return this.dateLivraisonSouhaite;
	}

	public void setDateLivraisonSouhaite(String dateLivraisonSouhaite) {
		this.dateLivraisonSouhaite = dateLivraisonSouhaite;
	}

	@Column(name = "dateLivraisonEffective", length = 254)
	public String getDateLivraisonEffective() {
		return this.dateLivraisonEffective;
	}

	public void setDateLivraisonEffective(String dateLivraisonEffective) {
		this.dateLivraisonEffective = dateLivraisonEffective;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "idAuteurCreation")
	public Integer getIdAuteurCreation() {
		return this.idAuteurCreation;
	}

	public void setIdAuteurCreation(Integer idAuteurCreation) {
		this.idAuteurCreation = idAuteurCreation;
	}

	@Column(name = "idAuteurModification")
	public Integer getIdAuteurModification() {
		return this.idAuteurModification;
	}

	public void setIdAuteurModification(Integer idAuteurModification) {
		this.idAuteurModification = idAuteurModification;
	}

}
