package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fournisseurs generated by hbm2java
 */
@Entity
@Table(name = "fournisseurs", catalog = "corepharma")
public class Fournisseurs implements java.io.Serializable {

	private Integer idFournisseur;
	private Integer idEtatFournisseur;
	private Integer idAlarme;
	private String nomFournisseur;
	private String codeFournisseur;
	private String tel;
	private String adresse;
	private String dateCreation;
	private String dateModification;
	private Integer idAuteurCreation;
	private Integer idAuteurModification;

	public Fournisseurs() {
	}

	public Fournisseurs(Integer idEtatFournisseur, Integer idAlarme,
			String nomFournisseur, String codeFournisseur, String tel,
			String adresse, String dateCreation, String dateModification,
			Integer idAuteurCreation, Integer idAuteurModification) {
		this.idEtatFournisseur = idEtatFournisseur;
		this.idAlarme = idAlarme;
		this.nomFournisseur = nomFournisseur;
		this.codeFournisseur = codeFournisseur;
		this.tel = tel;
		this.adresse = adresse;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.idAuteurCreation = idAuteurCreation;
		this.idAuteurModification = idAuteurModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFournisseur", unique = true, nullable = false)
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "idEtatFournisseur")
	public Integer getIdEtatFournisseur() {
		return this.idEtatFournisseur;
	}

	public void setIdEtatFournisseur(Integer idEtatFournisseur) {
		this.idEtatFournisseur = idEtatFournisseur;
	}

	@Column(name = "idAlarme")
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "nomFournisseur", length = 254)
	public String getNomFournisseur() {
		return this.nomFournisseur;
	}

	public void setNomFournisseur(String nomFournisseur) {
		this.nomFournisseur = nomFournisseur;
	}

	@Column(name = "codeFournisseur", length = 254)
	public String getCodeFournisseur() {
		return this.codeFournisseur;
	}

	public void setCodeFournisseur(String codeFournisseur) {
		this.codeFournisseur = codeFournisseur;
	}

	@Column(name = "tel", length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "idAuteurCreation")
	public Integer getIdAuteurCreation() {
		return this.idAuteurCreation;
	}

	public void setIdAuteurCreation(Integer idAuteurCreation) {
		this.idAuteurCreation = idAuteurCreation;
	}

	@Column(name = "idAuteurModification")
	public Integer getIdAuteurModification() {
		return this.idAuteurModification;
	}

	public void setIdAuteurModification(Integer idAuteurModification) {
		this.idAuteurModification = idAuteurModification;
	}

}
