package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modedereglement generated by hbm2java
 */
@Entity
@Table(name = "modedereglement", catalog = "corepharma")
public class Modedereglement implements java.io.Serializable {

	private Integer idMode;
	private String nomMode;

	public Modedereglement() {
	}

	public Modedereglement(String nomMode) {
		this.nomMode = nomMode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMode", unique = true, nullable = false)
	public Integer getIdMode() {
		return this.idMode;
	}

	public void setIdMode(Integer idMode) {
		this.idMode = idMode;
	}

	@Column(name = "nomMode", length = 254)
	public String getNomMode() {
		return this.nomMode;
	}

	public void setNomMode(String nomMode) {
		this.nomMode = nomMode;
	}

}
