package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modedereglement generated by hbm2java
 */
@Entity
@Table(name = "modedereglement", catalog = "corepharma")
public class Modedereglement implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5289587956314161677L;
	private Integer idMode;
	private String nomMode;
	private Set<Commandes> modeReglementCommandes;
	private Set<Ventes> modeReglementVentes;
	
	public Modedereglement() {
	}

	public Modedereglement(String nomMode) {
		this.nomMode = nomMode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMode", unique = true, nullable = false)
	public Integer getIdMode() {
		return this.idMode;
	}

	public void setIdMode(Integer idMode) {
		this.idMode = idMode;
	}

	@Column(name = "nomMode", length = 254)
	public String getNomMode() {
		return this.nomMode;
	}

	public void setNomMode(String nomMode) {
		this.nomMode = nomMode;
	}

	public Set<Commandes> getModeReglementCommandes() {
		return modeReglementCommandes;
	}

	public void setModeReglementCommandes(Set<Commandes> modeReglementCommandes) {
		this.modeReglementCommandes = modeReglementCommandes;
	}

	public Set<Ventes> getModeReglementVentes() {
		return modeReglementVentes;
	}

	public void setModeReglementVentes(Set<Ventes> modeReglementVentes) {
		this.modeReglementVentes = modeReglementVentes;
	}

	
}
