package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pharmacies generated by hbm2java
 */
@Entity
@Table(name = "pharmacies", catalog = "corepharma")
public class Pharmacies implements java.io.Serializable {

	private Integer idPharmacie;
	private String nomPharmacie;
	private String codePharmacie;
	private String numeroLicence;
	private String nomProprietaire;

	public Pharmacies() {
	}

	public Pharmacies(String nomPharmacie, String codePharmacie,
			String numeroLicence, String nomProprietaire) {
		this.nomPharmacie = nomPharmacie;
		this.codePharmacie = codePharmacie;
		this.numeroLicence = numeroLicence;
		this.nomProprietaire = nomProprietaire;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPharmacie", unique = true, nullable = false)
	public Integer getIdPharmacie() {
		return this.idPharmacie;
	}

	public void setIdPharmacie(Integer idPharmacie) {
		this.idPharmacie = idPharmacie;
	}

	@Column(name = "nomPharmacie", length = 254)
	public String getNomPharmacie() {
		return this.nomPharmacie;
	}

	public void setNomPharmacie(String nomPharmacie) {
		this.nomPharmacie = nomPharmacie;
	}

	@Column(name = "codePharmacie", length = 254)
	public String getCodePharmacie() {
		return this.codePharmacie;
	}

	public void setCodePharmacie(String codePharmacie) {
		this.codePharmacie = codePharmacie;
	}

	@Column(name = "numeroLicence", length = 254)
	public String getNumeroLicence() {
		return this.numeroLicence;
	}

	public void setNumeroLicence(String numeroLicence) {
		this.numeroLicence = numeroLicence;
	}

	@Column(name = "nomProprietaire", length = 254)
	public String getNomProprietaire() {
		return this.nomProprietaire;
	}

	public void setNomProprietaire(String nomProprietaire) {
		this.nomProprietaire = nomProprietaire;
	}

}
