package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Typeclients generated by hbm2java
 */
@Entity
@Table(name = "typeclients", catalog = "corepharma")
public class Typeclients implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1872296338602181874L;
	private Integer idType;
	private String nomType;
	private Set<Clients> typeClients;

	public Typeclients() {
	}

	public Typeclients(String nomType) {
		this.nomType = nomType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idType", unique = true, nullable = false)
	public Integer getIdType() {
		return this.idType;
	}

	public void setIdType(Integer idType) {
		this.idType = idType;
	}

	@Column(name = "nomType", length = 254)
	public String getNomType() {
		return this.nomType;
	}

	public void setNomType(String nomType) {
		this.nomType = nomType;
	}

	public Set<Clients> getTypeClients() {
		return typeClients;
	}

	public void setTypeClients(Set<Clients> typeClients) {
		this.typeClients = typeClients;
	}

	
}
