package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ventes generated by hbm2java
 */
@Entity
@Table(name = "ventes", catalog = "corepharma")
public class Ventes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7896342381667417920L;
	private Integer idVente;
	private Integer idMode;
	private Integer idGestion;
	private Integer etatVente;
	private String dateCreation;
	private String dateModification;
	private String idAuteurCreation;
	private String idAuteurModification;
	private String codeVente;
	private Integer montantRecu;
	private Integer montantVente;
	private Set<Produits> produitsVentes;

	public Ventes() {
	}

	public Ventes(Integer idMode, Integer idGestion, Integer etatVente,
			String dateCreation, String dateModification,
			String idAuteurCreation, String idAuteurModification,
			String codeVente, Integer montantRecu, Integer montantVente) {
		this.idMode = idMode;
		this.idGestion = idGestion;
		this.etatVente = etatVente;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.idAuteurCreation = idAuteurCreation;
		this.idAuteurModification = idAuteurModification;
		this.codeVente = codeVente;
		this.montantRecu = montantRecu;
		this.montantVente = montantVente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idVente", unique = true, nullable = false)
	public Integer getIdVente() {
		return this.idVente;
	}

	public void setIdVente(Integer idVente) {
		this.idVente = idVente;
	}

	@Column(name = "idMode")
	public Integer getIdMode() {
		return this.idMode;
	}

	public void setIdMode(Integer idMode) {
		this.idMode = idMode;
	}

	@Column(name = "idGestion")
	public Integer getIdGestion() {
		return this.idGestion;
	}

	public void setIdGestion(Integer idGestion) {
		this.idGestion = idGestion;
	}

	@Column(name = "etatVente")
	public Integer getEtatVente() {
		return this.etatVente;
	}

	public void setEtatVente(Integer etatVente) {
		this.etatVente = etatVente;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "idAuteurCreation", length = 254)
	public String getIdAuteurCreation() {
		return this.idAuteurCreation;
	}

	public void setIdAuteurCreation(String idAuteurCreation) {
		this.idAuteurCreation = idAuteurCreation;
	}

	@Column(name = "idAuteurModification", length = 254)
	public String getIdAuteurModification() {
		return this.idAuteurModification;
	}

	public void setIdAuteurModification(String idAuteurModification) {
		this.idAuteurModification = idAuteurModification;
	}

	@Column(name = "codeVente", length = 254)
	public String getCodeVente() {
		return this.codeVente;
	}

	public void setCodeVente(String codeVente) {
		this.codeVente = codeVente;
	}

	@Column(name = "montantRecu", precision = 8, scale = 0)
	public Integer getMontantRecu() {
		return this.montantRecu;
	}

	public void setMontantRecu(Integer montantRecu) {
		this.montantRecu = montantRecu;
	}

	@Column(name = "montantVente", precision = 8, scale = 0)
	public Integer getMontantVente() {
		return this.montantVente;
	}

	public void setMontantVente(Integer montantVente) {
		this.montantVente = montantVente;
	}

	public Set<Produits> getProduitsVentes() {
		return produitsVentes;
	}

	public void setProduitsVentes(Set<Produits> produitsVentes) {
		this.produitsVentes = produitsVentes;
	}

	
}
