package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Aclientsadresses generated by hbm2java
 */
@Entity
@Table(name = "aclientsadresses", catalog = "corepharma")
public class Aclientsadresses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6767941296819902903L;
	private AclientsadressesId id;

	public Aclientsadresses() {
	}

	public Aclientsadresses(AclientsadressesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idClient", column = @Column(name = "idClient")),
			@AttributeOverride(name = "idAdresse", column = @Column(name = "idAdresse")) })
	public AclientsadressesId getId() {
		return this.id;
	}

	public void setId(AclientsadressesId id) {
		this.id = id;
	}

}
