package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcommandesproduitsId generated by hbm2java
 */
@Embeddable
public class AcommandesproduitsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5354557005036398575L;
	private Integer idProduit;
	private Integer idCommande;

	public AcommandesproduitsId() {
	}

	public AcommandesproduitsId(Integer idProduit, Integer idCommande) {
		this.idProduit = idProduit;
		this.idCommande = idCommande;
	}

	@Column(name = "idProduit")
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "idCommande")
	public Integer getIdCommande() {
		return this.idCommande;
	}

	public void setIdCommande(Integer idCommande) {
		this.idCommande = idCommande;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcommandesproduitsId))
			return false;
		AcommandesproduitsId castOther = (AcommandesproduitsId) other;

		return ((this.getIdProduit() == castOther.getIdProduit()) || (this
				.getIdProduit() != null
				&& castOther.getIdProduit() != null && this.getIdProduit()
				.equals(castOther.getIdProduit())))
				&& ((this.getIdCommande() == castOther.getIdCommande()) || (this
						.getIdCommande() != null
						&& castOther.getIdCommande() != null && this
						.getIdCommande().equals(castOther.getIdCommande())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdProduit() == null ? 0 : this.getIdProduit().hashCode());
		result = 37
				* result
				+ (getIdCommande() == null ? 0 : this.getIdCommande()
						.hashCode());
		return result;
	}

}
