package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Adresses generated by hbm2java
 */
@Entity
@Table(name = "adresses", catalog = "corepharma")
public class Adresses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4463846700748032264L;
	private Integer idAdresse;
	private String adresse;
	private String ville;
	private String codepostal;
	private String pays;
	Set<Clients> adresseClient;
	Set<Fournisseurs> adresseFournisseur;
	Set<Utilisateurs> adresseUser;

	public Adresses() {
	}

	public Adresses(String adresse, String ville, String codepostal, String pays) {
		this.adresse = adresse;
		this.ville = ville;
		this.codepostal = codepostal;
		this.pays = pays;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAdresse", unique = true, nullable = false)
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	@Column(name = "adresse", length = 254)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "ville", length = 254)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "codepostal", length = 254)
	public String getCodepostal() {
		return this.codepostal;
	}

	public void setCodepostal(String codepostal) {
		this.codepostal = codepostal;
	}

	@Column(name = "pays", length = 254)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	public Set<Clients> getAdresseClient() {
		return adresseClient;
	}

	public void setAdresseClient(Set<Clients> adresseClient) {
		this.adresseClient = adresseClient;
	}

	public Set<Fournisseurs> getAdresseFournisseur() {
		return adresseFournisseur;
	}

	public void setAdresseFournisseur(Set<Fournisseurs> adresseFournisseur) {
		this.adresseFournisseur = adresseFournisseur;
	}

	public Set<Utilisateurs> getAdresseUser() {
		return adresseUser;
	}

	public void setAdresseUser(Set<Utilisateurs> adresseUser) {
		this.adresseUser = adresseUser;
	}

	
}
