package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AforunisseursadressesId generated by hbm2java
 */
@Embeddable
public class AforunisseursadressesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2545394333941404938L;
	private Integer idFournisseur;
	private Integer idAdresse;

	public AforunisseursadressesId() {
	}

	public AforunisseursadressesId(Integer idFournisseur, Integer idAdresse) {
		this.idFournisseur = idFournisseur;
		this.idAdresse = idAdresse;
	}

	@Column(name = "idFournisseur")
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "idAdresse")
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AforunisseursadressesId))
			return false;
		AforunisseursadressesId castOther = (AforunisseursadressesId) other;

		return ((this.getIdFournisseur() == castOther.getIdFournisseur()) || (this
				.getIdFournisseur() != null
				&& castOther.getIdFournisseur() != null && this
				.getIdFournisseur().equals(castOther.getIdFournisseur())))
				&& ((this.getIdAdresse() == castOther.getIdAdresse()) || (this
						.getIdAdresse() != null
						&& castOther.getIdAdresse() != null && this
						.getIdAdresse().equals(castOther.getIdAdresse())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdFournisseur() == null ? 0 : this.getIdFournisseur()
						.hashCode());
		result = 37 * result
				+ (getIdAdresse() == null ? 0 : this.getIdAdresse().hashCode());
		return result;
	}

}
