package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Alarmes generated by hbm2java
 */
@Entity
@Table(name="alarmes"
    ,catalog="corepharma"
)
public class Alarmes  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 283284500873649798L;
	private Integer idAlarme;
     private Integer idEtatAlarme;
     private String dateAlarme;

    public Alarmes() {
    }

    public Alarmes(Integer idEtatAlarme, String dateAlarme) {
       this.idEtatAlarme = idEtatAlarme;
       this.dateAlarme = dateAlarme;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idAlarme", unique=true, nullable=false)
    public Integer getIdAlarme() {
        return this.idAlarme;
    }
    
    public void setIdAlarme(Integer idAlarme) {
        this.idAlarme = idAlarme;
    }

    
    @Column(name="idEtatAlarme")
    public Integer getIdEtatAlarme() {
        return this.idEtatAlarme;
    }
    
    public void setIdEtatAlarme(Integer idEtatAlarme) {
        this.idEtatAlarme = idEtatAlarme;
    }

    
    @Column(name="dateAlarme", length=254)
    public String getDateAlarme() {
        return this.dateAlarme;
    }
    
    public void setDateAlarme(String dateAlarme) {
        this.dateAlarme = dateAlarme;
    }




}


