package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AssoventesproduitsId generated by hbm2java
 */
@Embeddable
public class AssoventesproduitsId implements java.io.Serializable {

	private Integer idVente;
	private Integer idProduit;

	public AssoventesproduitsId() {
	}

	public AssoventesproduitsId(Integer idVente, Integer idProduit) {
		this.idVente = idVente;
		this.idProduit = idProduit;
	}

	@Column(name = "idVente")
	public Integer getIdVente() {
		return this.idVente;
	}

	public void setIdVente(Integer idVente) {
		this.idVente = idVente;
	}

	@Column(name = "idProduit")
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssoventesproduitsId))
			return false;
		AssoventesproduitsId castOther = (AssoventesproduitsId) other;

		return ((this.getIdVente() == castOther.getIdVente()) || (this
				.getIdVente() != null
				&& castOther.getIdVente() != null && this.getIdVente().equals(
				castOther.getIdVente())))
				&& ((this.getIdProduit() == castOther.getIdProduit()) || (this
						.getIdProduit() != null
						&& castOther.getIdProduit() != null && this
						.getIdProduit().equals(castOther.getIdProduit())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdVente() == null ? 0 : this.getIdVente().hashCode());
		result = 37 * result
				+ (getIdProduit() == null ? 0 : this.getIdProduit().hashCode());
		return result;
	}

}
