package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AutilisateursadressesId generated by hbm2java
 */
@Embeddable
public class AutilisateursadressesId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8230855007472141537L;
	private Integer idUtilisateur;
	private Integer idAdresse;

	public AutilisateursadressesId() {
	}

	public AutilisateursadressesId(Integer idUtilisateur, Integer idAdresse) {
		this.idUtilisateur = idUtilisateur;
		this.idAdresse = idAdresse;
	}

	@Column(name = "idUtilisateur")
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "idAdresse")
	public Integer getIdAdresse() {
		return this.idAdresse;
	}

	public void setIdAdresse(Integer idAdresse) {
		this.idAdresse = idAdresse;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AutilisateursadressesId))
			return false;
		AutilisateursadressesId castOther = (AutilisateursadressesId) other;

		return ((this.getIdUtilisateur() == castOther.getIdUtilisateur()) || (this
				.getIdUtilisateur() != null
				&& castOther.getIdUtilisateur() != null && this
				.getIdUtilisateur().equals(castOther.getIdUtilisateur())))
				&& ((this.getIdAdresse() == castOther.getIdAdresse()) || (this
						.getIdAdresse() != null
						&& castOther.getIdAdresse() != null && this
						.getIdAdresse().equals(castOther.getIdAdresse())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdUtilisateur() == null ? 0 : this.getIdUtilisateur()
						.hashCode());
		result = 37 * result
				+ (getIdAdresse() == null ? 0 : this.getIdAdresse().hashCode());
		return result;
	}

}
