package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Autilisateursadresses generated by hbm2java
 */
@Entity
@Table(name = "autilisateursadresses", catalog = "corepharma")
public class Autilisateursadresses implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 53772460581264214L;
	private AutilisateursadressesId id;

	public Autilisateursadresses() {
	}

	public Autilisateursadresses(AutilisateursadressesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "idUtilisateur", column = @Column(name = "idUtilisateur")),
			@AttributeOverride(name = "idAdresse", column = @Column(name = "idAdresse")) })
	public AutilisateursadressesId getId() {
		return this.id;
	}

	public void setId(AutilisateursadressesId id) {
		this.id = id;
	}

}
