package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Categorieutilisateurs generated by hbm2java
 */
@Entity
@Table(name = "categorieutilisateurs", catalog = "corepharma")
public class Categorieutilisateurs implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 457687241908845731L;
	private Integer idCategorie;
	private String nomCategorie;
	Set<Utilisateurs> utilisateurs;

	public Categorieutilisateurs() {
	}

	public Categorieutilisateurs(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCategorie", unique = true, nullable = false)
	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "nomCategorie", length = 254)
	public String getNomCategorie() {
		return this.nomCategorie;
	}

	public void setNomCategorie(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	public Set<Utilisateurs> getUtilisateurs() {
		return utilisateurs;
	}

	public void setUtilisateurs(Set<Utilisateurs> utilisateurs) {
		this.utilisateurs = utilisateurs;
	}

	
}
