package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comptesbancaires generated by hbm2java
 */
@Entity
@Table(name = "comptesbancaires", catalog = "corepharma")
public class Comptesbancaires implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6329061363480174378L;
	private Integer idCompte;
	private Integer idClient;
	private Integer idFournisseur;
	private String codeBanque;
	private String codeGuichet;
	private String numeroCompte;
	private String cleRib;
	private String iban;
	private String bicAdresseSwift;

	public Comptesbancaires() {
	}

	public Comptesbancaires(Integer idClient, Integer idFournisseur,
			String codeBanque, String codeGuichet, String numeroCompte,
			String cleRib, String iban, String bicAdresseSwift) {
		this.idClient = idClient;
		this.idFournisseur = idFournisseur;
		this.codeBanque = codeBanque;
		this.codeGuichet = codeGuichet;
		this.numeroCompte = numeroCompte;
		this.cleRib = cleRib;
		this.iban = iban;
		this.bicAdresseSwift = bicAdresseSwift;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCompte", unique = true, nullable = false)
	public Integer getIdCompte() {
		return this.idCompte;
	}

	public void setIdCompte(Integer idCompte) {
		this.idCompte = idCompte;
	}

	@Column(name = "idClient")
	public Integer getIdClient() {
		return this.idClient;
	}

	public void setIdClient(Integer idClient) {
		this.idClient = idClient;
	}

	@Column(name = "idFournisseur")
	public Integer getIdFournisseur() {
		return this.idFournisseur;
	}

	public void setIdFournisseur(Integer idFournisseur) {
		this.idFournisseur = idFournisseur;
	}

	@Column(name = "codeBanque", length = 254)
	public String getCodeBanque() {
		return this.codeBanque;
	}

	public void setCodeBanque(String codeBanque) {
		this.codeBanque = codeBanque;
	}

	@Column(name = "codeGuichet", length = 254)
	public String getCodeGuichet() {
		return this.codeGuichet;
	}

	public void setCodeGuichet(String codeGuichet) {
		this.codeGuichet = codeGuichet;
	}

	@Column(name = "numeroCompte", length = 254)
	public String getNumeroCompte() {
		return this.numeroCompte;
	}

	public void setNumeroCompte(String numeroCompte) {
		this.numeroCompte = numeroCompte;
	}

	@Column(name = "cleRib", length = 254)
	public String getCleRib() {
		return this.cleRib;
	}

	public void setCleRib(String cleRib) {
		this.cleRib = cleRib;
	}

	@Column(name = "iban", length = 254)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "bicAdresseSwift", length = 254)
	public String getBicAdresseSwift() {
		return this.bicAdresseSwift;
	}

	public void setBicAdresseSwift(String bicAdresseSwift) {
		this.bicAdresseSwift = bicAdresseSwift;
	}

}
