package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Etatalarme generated by hbm2java
 */
@Entity
@Table(name = "etatalarme", catalog = "corepharma")
public class Etatalarme implements java.io.Serializable {

	private Integer idEtatAlarme;
	private Integer nomEtatAlarme;

	public Etatalarme() {
	}

	public Etatalarme(Integer nomEtatAlarme) {
		this.nomEtatAlarme = nomEtatAlarme;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEtatAlarme", unique = true, nullable = false)
	public Integer getIdEtatAlarme() {
		return this.idEtatAlarme;
	}

	public void setIdEtatAlarme(Integer idEtatAlarme) {
		this.idEtatAlarme = idEtatAlarme;
	}

	@Column(name = "nomEtatAlarme")
	public Integer getNomEtatAlarme() {
		return this.nomEtatAlarme;
	}

	public void setNomEtatAlarme(Integer nomEtatAlarme) {
		this.nomEtatAlarme = nomEtatAlarme;
	}

}
