package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Etatalarme generated by hbm2java
 */
@Entity
@Table(name = "etatalarme", catalog = "corepharma")
public class Etatalarme implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1122476264544248653L;
	private Integer idEtatAlarme;
	private Integer nomEtatAlarme;
	private Set<Alarmes> alarmes;

	public Etatalarme() {
	}

	public Etatalarme(Integer nomEtatAlarme) {
		this.nomEtatAlarme = nomEtatAlarme;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEtatAlarme", unique = true, nullable = false)
	public Integer getIdEtatAlarme() {
		return this.idEtatAlarme;
	}

	public void setIdEtatAlarme(Integer idEtatAlarme) {
		this.idEtatAlarme = idEtatAlarme;
	}

	@Column(name = "nomEtatAlarme")
	public Integer getNomEtatAlarme() {
		return this.nomEtatAlarme;
	}

	public void setNomEtatAlarme(Integer nomEtatAlarme) {
		this.nomEtatAlarme = nomEtatAlarme;
	}

	public Set<Alarmes> getAlarmes() {
		return alarmes;
	}

	public void setAlarmes(Set<Alarmes> alarmes) {
		this.alarmes = alarmes;
	}

	
}
