package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pharmacies generated by hbm2java
 */
@Entity
@Table(name = "pharmacies", catalog = "corepharma")
public class Pharmacies implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8364265608089164680L;
	private Integer idPharmacie;
	private String nomPharmacie;
	private String codePharmacie;
	private String numeroLicence;
	private String nomProprietaire;
	private Integer etatPharmacie;

	public Pharmacies() {
	}

	public Pharmacies(String nomPharmacie, String codePharmacie,
			String numeroLicence, String nomProprietaire, Integer etatPharmacie) {
		this.nomPharmacie = nomPharmacie;
		this.codePharmacie = codePharmacie;
		this.numeroLicence = numeroLicence;
		this.nomProprietaire = nomProprietaire;
		this.etatPharmacie = etatPharmacie;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPharmacie", unique = true, nullable = false)
	public Integer getIdPharmacie() {
		return this.idPharmacie;
	}

	public void setIdPharmacie(Integer idPharmacie) {
		this.idPharmacie = idPharmacie;
	}

	@Column(name = "nomPharmacie", length = 254)
	public String getNomPharmacie() {
		return this.nomPharmacie;
	}

	public void setNomPharmacie(String nomPharmacie) {
		this.nomPharmacie = nomPharmacie;
	}

	@Column(name = "codePharmacie", length = 254)
	public String getCodePharmacie() {
		return this.codePharmacie;
	}

	public void setCodePharmacie(String codePharmacie) {
		this.codePharmacie = codePharmacie;
	}

	@Column(name = "numeroLicence", length = 254)
	public String getNumeroLicence() {
		return this.numeroLicence;
	}

	public void setNumeroLicence(String numeroLicence) {
		this.numeroLicence = numeroLicence;
	}

	@Column(name = "nomProprietaire", length = 254)
	public String getNomProprietaire() {
		return this.nomProprietaire;
	}

	public void setNomProprietaire(String nomProprietaire) {
		this.nomProprietaire = nomProprietaire;
	}

	@Column(name = "etatPharmacie")
	public Integer getEtatPharmacie() {
		return this.etatPharmacie;
	}

	public void setEtatPharmacie(Integer etatPharmacie) {
		this.etatPharmacie = etatPharmacie;
	}

}
