package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Produits generated by hbm2java
 */
@Entity
@Table(name = "produits", catalog = "corepharma")
public class Produits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 537332219318499949L;
	private Integer idProduit;
	private Integer idGestion;
	private Integer idAlarme;
	private String nomProduit;
	private String codeProduit;
	private Integer prixProduit;
	private Integer quantiteActuel;
	private Integer quantiteAlarme;
	private String datePeremption;
	private String dateCreation;
	private String dateModification;
	private Integer idAuteurCreation;
	private Integer idAuteurModification;
	private String produitPanier;
	private Set<Produits> venteProduits;
	private Set<Commandes> commandesProduits;

	public Produits() {
	}

	public Produits(Integer idGestion, Integer idAlarme, String nomProduit,
			String codeProduit, Integer prixProduit, Integer quantiteActuel,
			Integer quantiteAlarme, String datePeremption, String dateCreation,
			String dateModification, Integer idAuteurCreation,
			Integer idAuteurModification) {
		this.idGestion = idGestion;
		this.idAlarme = idAlarme;
		this.nomProduit = nomProduit;
		this.codeProduit = codeProduit;
		this.prixProduit = prixProduit;
		this.quantiteActuel = quantiteActuel;
		this.quantiteAlarme = quantiteAlarme;
		this.datePeremption = datePeremption;
		this.dateCreation = dateCreation;
		this.dateModification = dateModification;
		this.idAuteurCreation = idAuteurCreation;
		this.idAuteurModification = idAuteurModification;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idProduit", unique = true, nullable = false)
	public Integer getIdProduit() {
		return this.idProduit;
	}

	public void setIdProduit(Integer idProduit) {
		this.idProduit = idProduit;
	}

	@Column(name = "idGestion")
	public Integer getIdGestion() {
		return this.idGestion;
	}

	public void setIdGestion(Integer idGestion) {
		this.idGestion = idGestion;
	}

	@Column(name = "idAlarme")
	public Integer getIdAlarme() {
		return this.idAlarme;
	}

	public void setIdAlarme(Integer idAlarme) {
		this.idAlarme = idAlarme;
	}

	@Column(name = "nomProduit", length = 254)
	public String getNomProduit() {
		return this.nomProduit;
	}

	public void setNomProduit(String nomProduit) {
		this.nomProduit = nomProduit;
	}

	@Column(name = "codeProduit", length = 254)
	public String getCodeProduit() {
		return this.codeProduit;
	}

	public void setCodeProduit(String codeProduit) {
		this.codeProduit = codeProduit;
	}

	@Column(name = "prixProduit", precision = 8, scale = 0)
	public Integer getPrixProduit() {
		return this.prixProduit;
	}

	public void setPrixProduit(Integer prixProduit) {
		this.prixProduit = prixProduit;
	}

	@Column(name = "quantiteActuel")
	public Integer getQuantiteActuel() {
		return this.quantiteActuel;
	}

	public void setQuantiteActuel(Integer quantiteActuel) {
		this.quantiteActuel = quantiteActuel;
	}

	@Column(name = "quantiteAlarme")
	public Integer getQuantiteAlarme() {
		return this.quantiteAlarme;
	}

	public void setQuantiteAlarme(Integer quantiteAlarme) {
		this.quantiteAlarme = quantiteAlarme;
	}

	@Column(name = "datePeremption", length = 254)
	public String getDatePeremption() {
		return this.datePeremption;
	}

	public void setDatePeremption(String datePeremption) {
		this.datePeremption = datePeremption;
	}

	@Column(name = "dateCreation", length = 254)
	public String getDateCreation() {
		return this.dateCreation;
	}

	public void setDateCreation(String dateCreation) {
		this.dateCreation = dateCreation;
	}

	@Column(name = "dateModification", length = 254)
	public String getDateModification() {
		return this.dateModification;
	}

	public void setDateModification(String dateModification) {
		this.dateModification = dateModification;
	}

	@Column(name = "idAuteurCreation")
	public Integer getIdAuteurCreation() {
		return this.idAuteurCreation;
	}

	public void setIdAuteurCreation(Integer idAuteurCreation) {
		this.idAuteurCreation = idAuteurCreation;
	}

	@Column(name = "idAuteurModification")
	public Integer getIdAuteurModification() {
		return this.idAuteurModification;
	}

	public void setIdAuteurModification(Integer idAuteurModification) {
		this.idAuteurModification = idAuteurModification;
	}

	public String getProduitPanier() {
		return produitPanier;
	}

	public void setProduitPanier(String produitPanier) {
		this.produitPanier = produitPanier;
	}

	public Set<Produits> getVenteProduits() {
		return venteProduits;
	}

	public void setVenteProduits(Set<Produits> venteProduits) {
		this.venteProduits = venteProduits;
	}

	public Set<Commandes> getCommandesProduits() {
		return commandesProduits;
	}

	public void setCommandesProduits(Set<Commandes> commandesProduits) {
		this.commandesProduits = commandesProduits;
	}

	
}
