package corepharma.domain;

// default package
// Generated 12 juil. 2011 22:37:21 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Typeetatclient generated by hbm2java
 */
@Entity
@Table(name = "typeetatclient", catalog = "corepharma")
public class Typeetatclient implements java.io.Serializable {

	private Integer idEtatClient;
	private Integer nomEtatClient;

	public Typeetatclient() {
	}

	public Typeetatclient(Integer nomEtatClient) {
		this.nomEtatClient = nomEtatClient;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEtatClient", unique = true, nullable = false)
	public Integer getIdEtatClient() {
		return this.idEtatClient;
	}

	public void setIdEtatClient(Integer idEtatClient) {
		this.idEtatClient = idEtatClient;
	}

	@Column(name = "nomEtatClient")
	public Integer getNomEtatClient() {
		return this.nomEtatClient;
	}

	public void setNomEtatClient(Integer nomEtatClient) {
		this.nomEtatClient = nomEtatClient;
	}

}
