package corepharma.domain;

// default package
// Generated 16 juil. 2011 14:29:33 by Hibernate Tools 3.3.0.GA

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Typeetatclient generated by hbm2java
 */
@Entity
@Table(name = "typeetatclient", catalog = "corepharma")
public class Typeetatclient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6817861044383084709L;
	private Integer idEtatClient;
	private Integer nomEtatClient;
	private Set<Clients> typeEtatClients;
	private Set<Fournisseurs> typeEtatFournisseurs;

	public Typeetatclient() {
	}

	public Typeetatclient(Integer nomEtatClient) {
		this.nomEtatClient = nomEtatClient;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEtatClient", unique = true, nullable = false)
	public Integer getIdEtatClient() {
		return this.idEtatClient;
	}

	public void setIdEtatClient(Integer idEtatClient) {
		this.idEtatClient = idEtatClient;
	}

	@Column(name = "nomEtatClient")
	public Integer getNomEtatClient() {
		return this.nomEtatClient;
	}

	public void setNomEtatClient(Integer nomEtatClient) {
		this.nomEtatClient = nomEtatClient;
	}

	public Set<Clients> getTypeEtatClients() {
		return typeEtatClients;
	}

	public void setTypeEtatClients(Set<Clients> typeEtatClients) {
		this.typeEtatClients = typeEtatClients;
	}

	public Set<Fournisseurs> getTypeEtatFournisseurs() {
		return typeEtatFournisseurs;
	}

	public void setTypeEtatFournisseurs(Set<Fournisseurs> typeEtatFournisseurs) {
		this.typeEtatFournisseurs = typeEtatFournisseurs;
	}
	
	
}
